name: thot
description: "A journalism knowledge manufacturing platform."

version: 1.0.1+2

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.2
  go_router: ^16.2.4
  cupertino_icons: ^1.0.6
  http: ^1.5.0
  http_parser: ^4.1.2
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  json_annotation: ^4.8.1
  intl: ^0.20.2
  connectivity_plus: ^6.1.5
  internet_connection_checker: ^3.0.1
  retry: ^3.1.2
  logger: ^2.6.2
  flutter_dotenv: ^6.0.0
  path: ^1.9.0
  image_picker: ^1.2.0
  video_player: ^2.10.0
  chewie: ^1.13.0
  just_audio: ^0.10.5
  rxdart: ^0.28.0
  font_awesome_flutter: ^10.9.1
  url_launcher: ^6.3.2
  cached_network_image: ^3.2.3
  dio: ^5.9.0
  flutter_svg: ^2.2.1
  crop_your_image: ^2.0.0
  path_provider: ^2.1.1
  permission_handler: ^12.0.1
  typed_data: ^1.3.2
  cross_file: ^0.3.3+8
  file_selector: ^1.0.4
  image: ^4.5.4
  file_picker: ^10.3.3
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  video_compress: ^3.1.3
  # ffmpeg_kit_flutter_min: ^6.0.3
  video_thumbnail: ^0.5.6
  visibility_detector: ^0.4.0+2
  socket_io_client: ^3.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_slidable: ^4.0.3
  fl_chart: ^1.1.1
  timeago: ^3.7.1
  crypto: ^3.0.5
  convert: ^3.1.2
  meta: any
  package_info_plus: ^9.0.0
  collection: ^1.18.0
  web: ^1.1.0
  shimmer: ^3.0.0
  animations: ^2.0.8
  wakelock_plus: ^1.4.0
  markdown_widget: ^2.3.2+8
  lucide_icons: ^0.257.0

dev_dependencies:
  freezed: ^2.5.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.5.4
  flutter_launcher_icons: ^0.14.4
  mockito: ^5.4.6
  mocktail: ^1.0.4
  fake_async: ^1.3.1
  test: any
  network_image_mock: ^2.1.1
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Tailwind
      fonts:
        - asset: assets/fonts/tailwind_black.ttf
          weight: 900
    - family: BrunchesRough
      fonts:
        - asset: assets/fonts/brunches-rough.ttf
          weight: 400

  assets:
    - .env
    - assets/fonts/brunches-rough.ttf
    - assets/fonts/tailwind_black.ttf
    - assets/images/defaults/default_journalist_avatar.png
    - assets/images/defaults/default_user_avatar.png
    - assets/images/default_avatar.svg
    - assets/images/default_cover.png
    - assets/app_logo.png
    - assets/images/defaults/default-post-image.jpg
    - assets/logo.jpeg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/app_logo.png"
  remove_alpha_ios: true
